### PR TITLE
Transpile to ES5 during build process

### LINKED ISSUE #11: Compile ES6 build
Since Chrome 54 (the latest version at the time of writing) doesn't support some fancy features like `import`, I suggest bundling a dist version of jakecache transpiled into ES5.

(Ps. I fully intend to tackle these issues myself. Just noting them for future reference.)

### PR DESCRIPTION
**Pull request by ejb**
This fixes #11

### CODE REVIEW

**Comment by kenchris** [comment]
I am fine with this, @auchenberg ?

**Comment by kenchris** [comment]
Actually all browsers who support Service Workers support ES2015 with the exception of ES modules. So why wasn't the existing build step enough?

**Comment by ejb** [comment]
Hmm, maybe I was using the source files instead of the dist. I'll check and get back to you.

**Comment by ejb** [comment]
Yep, I was running the uncompiled src version. Closing this pull request.

**Pull request closed without merging**
